# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-KDF
version:      0.01
version_from: lib/Crypt/KDF/_base.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    Digest::SHA1:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
